import Link from "next/link"
import Head from 'next/head'

const Product = ({albums}) => {
  return (
    <>
     <Head>
        <title>WebDev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
    <h1 style={{textAlign: "center"}}>Dynamic Routing</h1> 
    <p style={{textAlign:"center", color:"red"}}>Click on any particulat list for dynamic routing</p>
    <br />
    {
      albums.map(album =><div style={{textAlign: "center"}}>
        <Link href={`/albums/${album.id}`} passHref>
        <ul>
          <li>
            {`${album.id}. ${album.title}`}
          </li>
        </ul>
        </Link>
        
        <br />
      </div>)
    }
    </>
  )
}

export default Product


export async function getStaticProps(){

  const response = await fetch(`https://jsonplaceholder.typicode.com/albums`)

  const resData = await response.json();


  return {
    props : {
      albums : resData.slice(0,6)
    }
  }


}