import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import { userAgent } from 'next/server'
// import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home({users}) {
  
  console.log(users)

  return (
    <>
     <Head>
        <title>CodesWear.com - Wear the code</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
     <h1>Next JS pre-rendering at server side</h1>
     <Link href="/users">Click Here for Client Side Data Fetching</Link>
     {
      users.map(user=> <div key={user.id}>
        <p>{user.name}</p>
        <p>{user.email}</p>
      </div>) 
     }
    </>
  )
}


export async function getStaticProps() {

  const response = await fetch(`https://jsonplaceholder.typicode.com/users`)

  const data = await response.json()

  return {
    props : {
      users : data
    }
  }

}